/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ub.government.sispdb.sispdb_gui.menu_utama;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author yhawin
 */
public class MainMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainMenuFrame() {
        initComponents();
        
        initViews();
    }
    
    void initViews(){
        this.pack();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemParameterSistem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemPengguna = new javax.swing.JMenuItem();
        menuItemLogPengguna = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemIkan = new javax.swing.JMenuItem();
        menuItemJenisIkan = new javax.swing.JMenuItem();
        menuItemSubKelas = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuItemUnitKerja = new javax.swing.JMenuItem();
        menuItemWilayahAdministratif = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemPerikananTangkapLaut = new javax.swing.JMenuItem();
        menuItemPerikananUmumDarat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemLaporanLaporan = new javax.swing.JMenuItem();
        menuItemExtractKeExcel = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemTabulasiKeText = new javax.swing.JMenuItem();
        menuItemSyncTaDariText = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItemDataMasterKeText = new javax.swing.JMenuItem();
        menuItemSyncMasterDariText = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemKeluar = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem19.setText("jMenuItem19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Setting");

        menuItemParameterSistem.setText("Parameter Sistem");
        jMenu1.add(menuItemParameterSistem);
        jMenu1.add(jSeparator1);

        menuItemPengguna.setText("Pengguna");
        menuItemPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPengguna);

        menuItemLogPengguna.setText("Log Pengguna");
        menuItemLogPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemLogPengguna);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Master");

        menuItemIkan.setText("IKAN");
        jMenu2.add(menuItemIkan);

        menuItemJenisIkan.setText("Jenis Ikan");
        jMenu2.add(menuItemJenisIkan);

        menuItemSubKelas.setText("Sub Kelas");
        jMenu2.add(menuItemSubKelas);
        jMenu2.add(jSeparator5);

        menuItemUnitKerja.setText("UPT/Unit Kerja");
        jMenu2.add(menuItemUnitKerja);

        menuItemWilayahAdministratif.setText("Wilayah Administratif");
        menuItemWilayahAdministratif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWilayahAdministratifActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemWilayahAdministratif);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("TABULASI");
        jMenu3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N

        menuItemPerikananTangkapLaut.setText("Perikanan Tangkap Laut");
        jMenu3.add(menuItemPerikananTangkapLaut);

        menuItemPerikananUmumDarat.setText("Perikanan Umum Darat");
        jMenu3.add(menuItemPerikananUmumDarat);
        jMenu3.add(jSeparator3);

        menuItemLaporanLaporan.setText("Laporan-Laporan");
        jMenu3.add(menuItemLaporanLaporan);

        menuItemExtractKeExcel.setText("Extract ke Excel");
        jMenu3.add(menuItemExtractKeExcel);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utilitas");

        menuItemTabulasiKeText.setText("Data TABULASI ke TEXT");
        jMenu4.add(menuItemTabulasiKeText);

        menuItemSyncTaDariText.setText("Syncronize TA dari TEXT");
        menuItemSyncTaDariText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSyncTaDariTextActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemSyncTaDariText);
        jMenu4.add(jSeparator4);

        menuItemDataMasterKeText.setText("Data Master ke TEXT");
        jMenu4.add(menuItemDataMasterKeText);

        menuItemSyncMasterDariText.setText("Syncronize Master dari TEXT");
        menuItemSyncMasterDariText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSyncMasterDariTextActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemSyncMasterDariText);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Keluar");

        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemLogout);
        jMenu5.add(jSeparator2);

        menuItemKeluar.setText("Keluar");
        jMenu5.add(menuItemKeluar);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuItemSyncMasterDariTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSyncMasterDariTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSyncMasterDariTextActionPerformed

    private void menuItemSyncTaDariTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSyncTaDariTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSyncTaDariTextActionPerformed

    private void menuItemWilayahAdministratifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWilayahAdministratifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemWilayahAdministratifActionPerformed

    private void menuItemPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPenggunaActionPerformed

    private void menuItemLogPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemLogPenggunaActionPerformed

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public JMenuItem getMenuItemDataMasterKeText() {
        return menuItemDataMasterKeText;
    }

    public JMenuItem getMenuItemExtractKeExcel() {
        return menuItemExtractKeExcel;
    }

    public JMenuItem getMenuItemJenisIkan() {
        return menuItemJenisIkan;
    }

    public JMenuItem getMenuItemKeluar() {
        return menuItemKeluar;
    }

    public JMenuItem getMenuItemLaporanLaporan() {
        return menuItemLaporanLaporan;
    }

    public JMenuItem getMenuItemLogPengguna() {
        return menuItemLogPengguna;
    }

    public JMenuItem getMenuItemLogout() {
        return menuItemLogout;
    }

    public JMenuItem getMenuItemParameterSistem() {
        return menuItemParameterSistem;
    }

    public JMenuItem getMenuItemPengguna() {
        return menuItemPengguna;
    }

    public JMenuItem getMenuItemPerikananTangkapLaut() {
        return menuItemPerikananTangkapLaut;
    }

    public JMenuItem getMenuItemPerikananUmumDarat() {
        return menuItemPerikananUmumDarat;
    }

    public JMenuItem getMenuItemSyncMasterDariText() {
        return menuItemSyncMasterDariText;
    }

    public JMenuItem getMenuItemSyncTaDariText() {
        return menuItemSyncTaDariText;
    }

    public JMenuItem getMenuItemTabulasiKeText() {
        return menuItemTabulasiKeText;
    }

    public JMenuItem getMenuItemWilayahAdministratif() {
        return menuItemWilayahAdministratif;
    }

    public JMenuItem getMenuItemIkan() {
        return menuItemIkan;
    }

    public JMenuItem getMenuItemSubKelas() {
        return menuItemSubKelas;
    }

    public JMenuItem getMenuItemUnitKerja() {
        return menuItemUnitKerja;
    }

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menuItemDataMasterKeText;
    private javax.swing.JMenuItem menuItemExtractKeExcel;
    private javax.swing.JMenuItem menuItemIkan;
    private javax.swing.JMenuItem menuItemJenisIkan;
    private javax.swing.JMenuItem menuItemKeluar;
    private javax.swing.JMenuItem menuItemLaporanLaporan;
    private javax.swing.JMenuItem menuItemLogPengguna;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemParameterSistem;
    private javax.swing.JMenuItem menuItemPengguna;
    private javax.swing.JMenuItem menuItemPerikananTangkapLaut;
    private javax.swing.JMenuItem menuItemPerikananUmumDarat;
    private javax.swing.JMenuItem menuItemSubKelas;
    private javax.swing.JMenuItem menuItemSyncMasterDariText;
    private javax.swing.JMenuItem menuItemSyncTaDariText;
    private javax.swing.JMenuItem menuItemTabulasiKeText;
    private javax.swing.JMenuItem menuItemUnitKerja;
    private javax.swing.JMenuItem menuItemWilayahAdministratif;
    // End of variables declaration//GEN-END:variables
}
